# Generated by Django 4.0.5 on 2022-07-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('cover', models.CharField(choices=[('Miękka', 'Miękka'), ('Twarda', 'Twarda')], default='Miękka', max_length=6)),
                ('publisher', models.TextField()),
                ('dateOfRelease', models.DateField()),
                ('dateOfPublishing', models.DateField(blank=True, default=None, null=True)),
                ('amountOfPages', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
